#!/usr/bin/env ruby
#
# Homebrew Bundle file
# - https://github.com/Homebrew/homebrew-bundle
#

# Pre-requisites
brew 'gcc'
brew 'git'
brew 'make'
brew 'stow'

# Bash
brew 'bash'
brew 'bash-completion'
brew 'vcprompt'

# Zsh
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Core shell packages
brew 'fasd'
brew 'neovim'
brew 'tmux'

# Other
brew 'git-open'
brew 'gpg'
brew 'openvpn'
brew 'pandoc'
brew 'tree'
brew 'wget'

# GNU utilities
# brew 'coreutils'
# brew 'findutils'
# brew 'gettext', link: true
# brew 'gnu-indent'
# brew 'gnu-sed'
# brew 'gnutls'
# brew 'grep'
# brew 'gnu-tar'
# brew 'gawk'

# Docker completion
brew 'docker-completion'
# brew 'docker-compose-completion'

# Node (nodenv) plugins - https://github.com/nodenv/nodenv/wiki/Plugins
# brew 'node', link: false
brew 'yarn'
brew 'node-build' # used by nodenv
brew 'nodenv'
tap 'nodenv/nodenv'
brew 'nodenv/nodenv/nodenv-aliases'
brew 'nodenv/nodenv/nodenv-default-packages'
brew 'nodenv/nodenv/nodenv-package-json-engine'
brew 'nodenv/nodenv/nodenv-package-rehash'
tap 'ouchxp/nodenv'
brew 'ouchxp/nodenv/nodenv-nvmrc'

# Python (pyenv)
# brew 'python', link: false
brew 'pyenv'
tap 'jawshooah/pyenv'
brew 'jawshooah/pyenv/pyenv-default-packages'

# Ruby (rbenv)
# brew 'ruby', link: false
brew 'ruby-build' # used by rbenv
brew 'rbenv'
brew 'rbenv-default-gems'

# Redis
tap 'ringohub/redis-cli'
brew 'redis-cli'

# Local Brewfile
local_brewfile = File.expand_path("~/.config/homebrew/Brewfile.local")
instance_eval File.read(local_brewfile) if File.exists?(local_brewfile)

#
# Only macOS beyond here
#

require 'os'
return unless OS.mac?

# macOS specific taps
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'

# Caskroom apps
# cask '1password'
cask 'dash'
cask 'docker'
cask 'homebrew/cask-versions/firefox-developer-edition'
cask 'google-chrome'
cask 'hammerspoon'
cask 'karabiner-elements'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'

# Caskroom fonts
tap 'homebrew/cask-fonts'
cask 'homebrew/cask-fonts/font-fira-code'
