#!/usr/bin/env ruby
#
# Homebrew Bundle file
# - https://github.com/Homebrew/homebrew-bundle
#

# Pre-requisites
brew 'git'
brew 'make'
brew 'stow'

# Bash
brew 'bash'
brew 'bash-completion@2'
brew 'vcprompt'

# Zsh
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Core shell packages
brew 'direnv'
brew 'fasd'
brew 'fzf'
brew 'neovim'
brew 'tmux'

# Gnu utilities
brew 'coreutils'
brew 'findutils'
brew 'gettext', link: true
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnutls'
brew 'grep'
brew 'gnu-tar'
brew 'gawk'
brew 'parallel'

# Other
brew 'ag'
brew 'asdf'
brew 'bats'
brew 'cmake'
brew 'direnv'
brew 'gcc'
brew 'git-open'
brew 'gpg'
brew 'hub'
brew 'htop'
brew 'jq'
# brew 'openvpn'
brew 'openssl'
brew 'pandoc'
brew 'ripgrep'
brew 'shfmt', link: true, overwrite: true
brew 'tree'
brew 'wget'

# Docker completion
brew 'docker-completion'
# brew 'docker-compose-completion'

# Dev related
brew 'yarn', args: ["ignore-dependencies"]

#
# Local Brewfile's
#

Dir.glob(File.expand_path('~/.config/homebrew/Brewfile.*')).each do |file|
  next if file.end_with?('.lock.json')
  instance_eval File.read(file) if File.exists?(file)
end

#
# Only macOS beyond here
#

require 'os'
return unless OS.mac?

# macOS specific taps
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'

# Caskroom apps
cask '1password'
cask '1password-cli'
cask 'dash'
cask 'docker'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iterm2'
cask 'karabiner-elements'
cask 'slack'
cask 'spotify'
cask 'veracrypt'
cask 'visual-studio-code'

# Caskroom fonts
tap 'homebrew/cask-fonts'
cask 'font-fira-code'
