#!/usr/bin/env bash
#
# description:
#   Lists relevant IP addresses
#
# usage:
#   ip_addresses
#

ip_addresses() {
  local INTERNAL_IP="$(ipconfig getifaddr en0)"
  local PUBLIC_IP="$(dig +short myip.opendns.com @resolver1.opendns.com)"
  print "Internal IP: $INTERNAL_IP"
  print "Public IP:   $PUBLIC_IP"
}
