#!/usr/bin/env zsh

# Create symlink to this directory
SOURCE_DOTFILES=$(cd $(dirname $0); pwd)
TARGET_DOTFILES="$HOME/.dotfiles"
if [[ ! -d "${TARGET_DOTFILES}" ]] && [[ ! -L "${TARGET_DOTFILES}" ]]; then
  ln -s "${SOURCE_DOTFILES}" "${TARGET_DOTFILES}"
fi

# Export dotfiles dir
DOTFILES_PATH="$HOME/.dotfiles"

# Import symlink helpers
source $DOTFILES_PATH/lib/functions/load_zsh_module
load_zsh_module $DOTFILES_PATH/plugins/dotfile_symlink

# Symlink directories
echo "\n=== Symlinking files & directories ===\n"
symlink_dotfile_dir "${DOTFILES_PATH}/config/bash"
symlink_dotfile_dir "${DOTFILES_PATH}/config/dev"
symlink_dotfile_dir "${DOTFILES_PATH}/config/macos"
symlink_dotfile_dir "${DOTFILES_PATH}/config/vim"
symlink_dotfile_dir "${DOTFILES_PATH}/config/zsh"
symlink_dotfile_dir "${DOTFILES_PATH}/local"
symlink_dotfile_dir "${DOTFILES_PATH}/secrets"

# Reload zsh
echo "\n=== Restarting your shell ===\n"
source ~/.zshrc
