#!/usr/bin/env zsh

# Check if zplug is installed
ZPLUG_HOME="${ZPLUG_HOME:-$HOME/.zplug}"
if [[ ! -d "${ZPLUG_HOME}" ]]; then
  git clone https://github.com/zplug/zplug "${HOME}/.zplug/repos/zplug/zplug"
  ln -s "${HOME}/.zplug/repos/zplug/zplug/init.zsh" "${HOME}/.zplug/init.zsh"
fi

# Create symlink to this directory
SOURCE_DOTFILES=$(cd $(dirname $0); pwd)
TARGET_DOTFILES="$HOME/.dotfiles"
if [[ ! -d "${TARGET_DOTFILES}" ]] && [[ ! -L "${TARGET_DOTFILES}" ]]; then
  ln -s "${SOURCE_DOTFILES}" "${TARGET_DOTFILES}"
fi

# Export dotfiles dir
DOTPATH="$HOME/.dotfiles"

# Source some helpers
source $DOTPATH/plugins/zsh-functions/functions/autoload_fpath
autoload_fpath $DOTPATH/plugins/zsh-functions/functions
load_zsh_module $DOTPATH/plugins/dotfiles

# Symlink directories
echo "\n=== Symlinking files & directories ===\n"
symlink_dotfile_dir "${DOTPATH}/config"
symlink_dotfile_dir "${DOTPATH}/local"
if [[ ! -d "${DOTPATH}/secrets" ]]; then
  symlink_dotfile_dir "${DOTPATH}/secrets"
fi

# Reload zsh
echo "\n=== Restarting your shell ===\n"
source ~/.zshrc
