-- This module allows us to enable/disable plugins if we want
-- the full LazyVim setup or not. Some plugins are always enabled
-- and some are not. This is a way to control that.

-- TODO: Make enabling/disabling plugins more flexible
local lazyvim_enabled = vim.g.lazyvim == true or false

return {
  { "akinsho/bufferline.nvim", enabled = lazyvim_enabled },
  { "catppuccin/nvim", enabled = lazyvim_enabled },
  { "dstein64/vim-startuptime", enabled = lazyvim_enabled },
  { "echasnovski/mini.ai", enabled = lazyvim_enabled },
  { "echasnovski/mini.bufremove", enabled = lazyvim_enabled },
  { "echasnovski/mini.comment", enabled = lazyvim_enabled },
  { "echasnovski/mini.indentscope", enabled = lazyvim_enabled },
  { "echasnovski/mini.pairs", enabled = lazyvim_enabled },
  { "echasnovski/mini.surround", enabled = lazyvim_enabled },
  { "folke/flash.nvim", enabled = lazyvim_enabled },
  { "folke/neoconf.nvim", enabled = lazyvim_enabled },
  { "folke/neodev.nvim", enabled = lazyvim_enabled },
  { "folke/noice.nvim", enabled = lazyvim_enabled },
  { "folke/persistence.nvim", enabled = lazyvim_enabled },
  { "folke/todo-comments.nvim", enabled = lazyvim_enabled },
  { "folke/tokyonight.nvim", enabled = lazyvim_enabled },
  { "folke/trouble.nvim", enabled = lazyvim_enabled },
  { "folke/which-key.nvim", enabled = true },
  { "hrsh7th/cmp-buffer", enabled = true },
  { "hrsh7th/cmp-nvim-lsp", enabled = true },
  { "hrsh7th/cmp-path", enabled = true },
  { "hrsh7th/nvim-cmp", enabled = true },
  { "JoosepAlviste/nvim-ts-context-commentstring", enabled = lazyvim_enabled },
  { "L3MON4D3/LuaSnip", enabled = lazyvim_enabled },
  { "lewis6991/gitsigns.nvim", enabled = lazyvim_enabled },
  { "lukas-reineke/indent-blankline.nvim", enabled = lazyvim_enabled },
  { "mason.nvim", enabled = true },
  { "mfussenegger/nvim-lint", enabled = lazyvim_enabled },
  { "MunifTanjim/nui.nvim", enabled = lazyvim_enabled },
  { "neovim/nvim-lspconfig", enabled = true },
  { "nvim-lspconfig", enabled = true },
  { "nvim-lua/plenary.nvim", enabled = true },
  { "nvim-lualine/lualine.nvim", enabled = lazyvim_enabled },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = lazyvim_enabled },
  { "nvim-telescope/telescope-fzf-native.nvim", enabled = true },
  { "nvim-telescope/telescope.nvim", enabled = true },
  { "nvim-tree/nvim-web-devicons", enabled = true },
  { "nvim-treesitter/nvim-treesitter-context", enabled = lazyvim_enabled },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = lazyvim_enabled },
  { "nvim-treesitter/nvim-treesitter", enabled = true },
  { "nvimdev/dashboard-nvim", enabled = lazyvim_enabled },
  { "rafamadriz/friendly-snippets", enabled = lazyvim_enabled },
  { "rcarriga/nvim-notify", enabled = lazyvim_enabled },
  { "RRethy/vim-illuminate", enabled = lazyvim_enabled },
  { "saadparwaiz1/cmp_luasnip", enabled = true },
  { "stevearc/conform.nvim", enabled = true },
  { "stevearc/dressing.nvim", enabled = true },
  { "williamboman/mason-lspconfig.nvim", enabled = true },
  { "windwp/nvim-ts-autotag", enabled = lazyvim_enabled },
}
