#!/usr/bin/env zsh

confirm() {
  local msg=$1

  [ -z "$1" ] && msg="Are you sure [y/N]?"
  echo -n "$msg "
  read answer
  case "${answer}" in
    [yY]|[yY][eE][sS])
      return 0
  esac
  return 1
}
