#!/usr/bin/env zsh

find_latest_file() {
  local dir=$1
  local pattern=$2

  [ -z "${dir}" ] && echo "Directory not provided" && return 1
  [ ! -d "${dir}" ] && echo "Directory does not exist" && return 1
  [ -z "${pattern}" ] && echo "Pattern not provided" && return 1

  # glob directory -> filter by pattern -> sort by date -> one result
  echo $(ls ${dir}/**/*(e:'[[ $REPLY =~ ${pattern} ]]':.om[1]))
}
