#!/usr/bin/env sh
#
# Common environment settings
#

# XDG configuration
# - https://wiki.archlinux.org/index.php/XDG_Base_Directory
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Dotfiles dir
export DOTFILES_DIR="${DOTFILES_DIR:-${HOME}/.dotfiles}"

# Terminal
export TERM=xterm

# Remap ~/.vimrc
export VIMINIT=":source $XDG_CONFIG_HOME/nvim/init.vim"

# Editor
export EDITOR=vi
export VISUAL="${EDITOR}"

# Colors
export CLICOLOR=1

# Pager
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
LESSKEY="${XDG_CONFIG_HOME}/less/keys"
LESS="-F -g -i -M -R -S -w -X -z-4"
LESSCHARSET="utf-8"
PAGER="less"

# Set the Less input preprocessor
if type lesspipe.sh >/dev/null 2>&1; then
  export LESSOPEN="|lesspipe.sh %s"
fi

# Load core utilities used by other scripts
source "${DOTFILES_DIR}/lib/init.sh"

# Append bin directories to path
prepend_path "${DOTFILES_DIR}/bin"
prepend_path "${HOME}/.local/bin"

# Load profile files into environment
if [[ -d "${XDG_CONFIG_HOME}/profile.d" ]]; then
  source_files_in ${XDG_CONFIG_HOME}/profile.d/*
fi
