#!/usr/bin/env sh
#
# Common environment settings
#
# - https://wiki.archlinux.org/index.php/XDG_Base_Directory
#

# XDG configuration
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Dotfiles dir
export DOTFILES_DIR="${DOTFILES_DIR:-${HOME}/.dotfiles}"

# Prepend bin directories to path
export PATH="${HOME}/.local/bin:${DOTFILES_DIR}/bin:$PATH"

# Terminal
export TERM=xterm

# Remap ~/.vimrc
export VIMINIT=":source $XDG_CONFIG_HOME/nvim/init.vim"

# Editor
export EDITOR=vi
export VISUAL="${EDITOR}"

# Colors
export CLICOLOR=1

# Gnu GPG
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"

# Pager
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
LESSKEY="${XDG_CONFIG_HOME}/less/keys"
LESS="-F -g -i -M -R -S -w -X -z-4"
LESSCHARSET="utf-8"
PAGER="less"

# Set the Less input preprocessor
if type lesspipe.sh >/dev/null 2>&1; then
  export LESSOPEN="|lesspipe.sh %s"
fi

# Set brew prefix if macos to avoid using "$(brew --prefix)"
if [[ "$OSTYPE" == darwin* ]]; then
  BREW_PREFIX="${BREW_PREFIX:-/usr/local}"
fi

# Load other profile files
if [[ -d "${XDG_CONFIG_HOME}/profile.d" ]]; then
  for file in ${XDG_CONFIG_HOME}/profile.d/*; do
    source $file
  done
fi
