#!/usr/bin/env bash
#
# description:
#   Returns a list of completions
#

set -e

command="$1"
if [ -z "$command" ]; then
  echo "Error: No command provided."
  dotfiles-help
  exit 1
fi

command_path="$(command -v "dotfiles-${command}")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide dotfiles completions" "$command_path" >/dev/null; then
  shift
  exec "$command_path" --complete "$@"
fi
