-- This module allows us to enable/disable plugins in a single place

return {
  -- always enabled
  { "akinsho/bufferline.nvim",                     enabled = false },
  { "dstein64/vim-startuptime",                    enabled = false },
  -- { "folke/neoconf.nvim",                          enabled = false },
  -- { "folke/persistence.nvim",                      enabled = false },
  -- { "folke/trouble.nvim",                          enabled = false },
  -- { "folke/which-key.nvim",                        enabled = false },
  -- { "echasnovski/mini.comment",                    enabled = false },
  -- { "echasnovski/mini.pairs",                      enabled = false },
  -- { "echasnovski/mini.surround",                   enabled = false },
  -- { "hrsh7th/cmp-buffer",                          enabled = false },
  -- { "hrsh7th/cmp-nvim-lsp",                        enabled = false },
  -- { "hrsh7th/cmp-path",                            enabled = false },
  -- { "hrsh7th/nvim-cmp",                            enabled = false },
  -- { "lewis6991/gitsigns.nvim",                     enabled = false },
  -- { "lukas-reineke/indent-blankline.nvim",         enabled = false },
  -- { "mason.nvim",                                  enabled = false },
  -- { "MunifTanjim/nui.nvim",                        enabled = false },
  -- { "neovim/nvim-lspconfig",                       enabled = false },
  -- { "nvim-lua/plenary.nvim",                       enabled = false },
  -- { "nvim-lualine/lualine.nvim",                   enabled = false },
  -- { "nvim-pack/nvim-spectre",                      enabled = false },
  -- { "nvim-neo-tree/neo-tree.nvim",                 enabled = false },
  -- { "nvim-telescope/telescope.nvim",               enabled = false },
  -- { "nvim-telescope/telescope-fzf-native.nvim",    enabled = false },
  -- { "nvim-tree/nvim-web-devicons",                 enabled = false },
  -- { "nvim-treesitter/nvim-treesitter",             enabled = false },
  -- { "nvimdev/dashboard-nvim",                      enabled = false },
  -- { "saadparwaiz1/cmp_luasnip",                    enabled = false },
  -- { "stevearc/conform.nvim",                       enabled = false },
  -- { "stevearc/dressing.nvim",                      enabled = false },
  -- { "williamboman/mason-lspconfig.nvim",           enabled = false },

  -- maybe/later list
  -- { "echasnovski/mini.ai", enabled = false },
  -- { "echasnovski/mini.bufremove", enabled = false },
  -- { "echasnovski/mini.indentscope", enabled = false },
  -- { "folke/flash.nvim", enabled = false },
  -- { "folke/neodev.nvim", enabled = false },
  -- { "folke/noice.nvim", enabled = false },
  -- { "folke/todo-comments.nvim", enabled = false },
  -- { "folke/tokyonight.nvim", enabled = false },
  -- { "JoosepAlviste/nvim-ts-context-commentstring", enabled = lazyvim_enabled },
  -- { "mfussenegger/nvim-lint", enabled = false },
  -- { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  -- { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  -- { "rafamadriz/friendly-snippets", enabled = false },
  -- { "rcarriga/nvim-notify", enabled = false },
  -- { "RRethy/vim-illuminate", enabled = false },
  -- { "windwp/nvim-ts-autotag", enabled = false },
}
