#!/usr/bin/env zsh
#
# description:
#   Update the dotfiles
#

set -e

ensure_directories() {
  mkdir -p "${DOTFILES_DIR}/repos"
  mkdir -p "${DOTFILES_DIR}/zfunctions"
}

run_packages_script() {
  local dotfiles_dir="${DOTFILES_DIR:-$HOME/.dotfiles}"

  pushd ${DOTFILES_DIR} >/dev/null

  local_packages_script="${DOTFILES_DIR}/local/packages.sh"

  if [ -e "${local_packages_script}" ]; then
    echo "Found local script at '${local_packages_script}'"
    ${local_packages_script}
  else
    ${DOTFILES_DIR}/packages.sh
  fi

  popd >/dev/null
}

run() {
  ensure_directories
  run_packages_script
  dotfiles-reload
}

run

exit 0
