#!/usr/bin/env bash
#
# description:
#   Installs or updates a github repo
#
# usage:
#   github-repo acme/package
#   github-repo acme/package --post-install 'make'
#

set -e

# Ensure certain directories are in place
mkdir -p "${DOTFILES_DIR}/repos"

# Create all symlinks
github-install $@
