#!/usr/bin/env zsh
#
# description:
#   Update the dotfiles
#

set -e

# Install repos
echo "Installing packages ..."
"${DOTFILES_DIR}/packages.sh"

# Symlink files
echo ""
dotfiles-link

# Reload the shell
echo ""
dotfiles-reload

exit 0
