#!/usr/bin/env bash
#
# description:
#   Returns the list of available commands
#

set -e

# The list of commands
COMMANDS=(
  backup
  commands
  help
  init
  profile
  setup
)

# Print out commands
{ for cmd in "${COMMANDS[@]}"; do
    echo $cmd
  done
} | sort | uniq
