#!/usr/bin/env bash
#
# description:
#   Symlinks dotfiles from a source -> target
#
# usage:
#   dotfiles link path/to/source path/to/target
#

set -e

pushd ${DOTFILES_DIR} >/dev/null
symlink $@
popd >/dev/null
