#!/usr/bin/env zsh
#
# description:
#   Setup script for install dotfiles
#

set -e

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
DOTFILES_SRC_DIR=$(cd ${DOTFILES_ROOT}/../..; pwd)

# Ensure the dotfiles home symlink is created and valid
if [[ -d "${DOTFILES_DIR}" ]] && [[ ! -L "${DOTFILES_DIR}" ]]; then
  echo >&2 "Error: Dotfiles home is a real directory"
  exit 1
elif [[ ! -L "${DOTFILES_DIR}" ]]; then
  echo "Creating dotfiles home symlink ... ${DOTFILES_DIR} -> ${DOTFILES_SRC_DIR}"
  ln -s "${DOTFILES_SRC_DIR}" "${DOTFILES_DIR}"
elif [[ ! -d "$(readlink "${DOTFILES_DIR}")" ]]; then
  echo "Replacing dotfiles home symlink ... ${DOTFILES_DIR} -> ${DOTFILES_SRC_DIR}"
  rm ${DOTFILES_DIR}
  ln -s "${DOTFILES_SRC_DIR}" "${DOTFILES_DIR}"
else
  echo "Dotfiles home is valid ... ${DOTFILES_DIR} -> ${DOTFILES_SRC_DIR}"
fi

# Run update
dotfiles-update
