# Starship prompt config: https://starship.rs/config/

scan_timeout = 30
command_timeout = 1000

[cmd_duration]
min_time = 0
style = "yellow"
# show_milliseconds = true

[docker_context]
disabled = true

[package]
disabled = true
