#!/usr/bin/env zsh
#
# description:
#   Setup script for install dotfiles
#

set -e

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
DOTFILES_SRC_DIR=$(cd ${DOTFILES_ROOT}/../..; pwd)
ZPLUG_HOME="${ZPLUG_HOME:-$HOME/.zplug}"

# Ensure the dotfiles home symlink is created and valid
if [[ -d "${DOTFILES_DIR}" ]] && [[ ! -L "${DOTFILES_DIR}" ]]; then
  echo >&2 "Error: Dotfiles home is a real directory"
  exit 1
elif [[ ! -L "${DOTFILES_DIR}" ]]; then
  echo "Creating dotfiles home symlink ... ${DOTFILES_DIR} -> ${DOTFILES_SRC_DIR}"
  ln -s "${DOTFILES_SRC_DIR}" "${DOTFILES_DIR}"
elif [[ ! -d "$(readlink "${DOTFILES_DIR}")" ]]; then
  echo "Replacing dotfiles home symlink ... ${DOTFILES_DIR} -> ${DOTFILES_SRC_DIR}"
  rm ${DOTFILES_DIR}
  ln -s "${DOTFILES_SRC_DIR}" "${DOTFILES_DIR}"
else
  echo "Dotfiles home is valid ... ${DOTFILES_DIR} -> ${DOTFILES_SRC_DIR}"
fi

# Symlink directories
dotfiles-link

# Initialize zplug
if [[ ! -d "${ZPLUG_HOME}" ]]; then
  echo "Installing zplug ..."
  git clone https://github.com/zplug/zplug "${ZPLUG_HOME}"
fi

# Install and update zplug packages
echo "\nUpdating zplug ..."
source "${ZPLUG_HOME}/init.zsh" || true
zplug install || true
zplug clear || true

# Reload zsh
echo "\nReloading ..."
source "$HOME/.zshrc"
