#!/usr/bin/env zsh
#
# description:
#   Returns the list of available commands
#

set -e

# The list of commands
COMMANDS=(
  backup
  commands
  help
  link
  reload
  setup
  time
  update
)

# Print out commands
{ for cmd in "${COMMANDS[@]}"; do
    echo $cmd
  done
} | sort | uniq
