#!/usr/bin/env zsh
#
# description:
#   Autoloads the functions within the specified path
#
# usage:
#   autoload_fpath ./path/to/functions
#

# Add directory to PATH if it exits
autoload_fpath() {
  local dir=$1
  local force=$2

  if [ -n $force ]; then
    fpath=($dir $fpath)
  else
    [ -d $dir ] && fpath=($dir $fpath)
  fi

  for func in $(find $dir -maxdepth 1 -type f); do
    funcfile=$(basename $func)
    autoload $funcfile
  done
}
