#!/usr/bin/env zsh
#
# description:
#   Finds the latest file based on a pattern
#
# usage:
#   find_latest_file ./directory/to/search "file_pattern_find"
#

find_latest_file() {
  local dir=$1
  local pattern=$2

  [ -z "${dir}" ] && echo "Directory not provided" && return 1
  [ ! -d "${dir}" ] && echo "Directory does not exist" && return 1
  [ -z "${pattern}" ] && echo "Pattern not provided" && return 1

  # glob directory -> filter by pattern -> sort by date -> one result
  echo $(ls ${dir}/**/*(e:'[[ $REPLY =~ ${pattern} ]]':.om[1]))
}
