#!/usr/bin/env zsh

# Prepands each string with the prefix
# Examples:
#   prepend_each '--switch' 'foo bar' = '--switch foo --switch bar'
function prepend_each {
  set -o shwordsplit

  local prefix=$1
  local arr="$2"
  local result=

  # for item in ${arr[@]}; do
  for item in $arr; do
    result="${result}${prefix} '$item' "
  done

  echo $result
}
