#!/usr/bin/env sh
#
# description:
#   Prompt for a confirmation message
#
# usage:
#   confirm "Do you want to continue? [y/N]'" && echo continuing ...
#

confirm() {
  local msg=$1

  [ -z "$1" ] && msg="Are you sure?"
  confirm_msg="${msg} [y/N]?"

  echo -n "$confirm_msg "
  read answer
  case "${answer}" in
    [yY]|[yY][eE][sS])
      return 0
  esac
  return 1
}
