#!/usr/bin/env ruby
#
# Homebrew Bundle file
# - https://github.com/Homebrew/homebrew-bundle
#

# Pre-requisites
# brew 'git'
# brew 'make'
# brew 'stow'

# Bash
# brew 'bash'
# brew 'bash-completion@2'

# Zsh
# brew 'zsh'
# brew 'zsh-autosuggestions'
# brew 'zsh-completions'
# brew 'zsh-history-substring-search'
# brew 'zsh-syntax-highlighting'

# Core shell packages
# brew 'asdf'
# brew 'bat'
# brew 'direnv'
# brew 'fasd'
# brew 'fzf'
# brew 'gh'
# brew 'jq'
# brew 'neovim'
# brew 'ripgrep'
# brew 'starship'
# brew 'tmux'

# Gnu utilities
# brew 'coreutils'
# brew 'gpg'

#
# Local Brewfile's
#

Dir.glob(File.expand_path('~/.config/homebrew/Brewfile.*')).each do |file|
  next if file.end_with?('.lock.json')
  instance_eval File.read(file) if File.exists?(file)
end

#
# Only macOS beyond here
#

require 'os'
return unless OS.mac?

# macOS specific taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'

# Caskroom apps
cask 'firefox-developer-edition'
cask 'hammerspoon'
cask 'iterm2'
cask 'karabiner-elements'
cask 'raycast'

# Caskroom fonts
cask 'font-fira-code'
cask 'font-fira-mono'
