# See https://mise.jdx.dev/configuration.html

[settings]
disable_backends = [""]
experimental = true
legacy_version_file = true
# libgit2 = false
python_venv_auto_create = true

[settings.pipx]
uvx = true

[settings.rust]
# Set in modules/rust/.config/environment.d/rust.conf since settings do not
# expand variables or support templates atm.
# cargo_home = "~/.local/share/cargo"
# rustup_home = "~/.local/share/rustup"

[tools]
bun = "latest"
cue = "0.11"
deno = "latest"
go = "latest"
java = "23"
# kotlin = "latest"
lua = "latest"
maven = "latest"
node = "23"
pitchfork = "latest"
python = "3.13"
ruby = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
