#!/usr/bin/env sh
#
# Setup macOS System
#

# Exit on error or unset variable
set -o nounset
set -o errexit
set -o pipefail

# Current directory
local dir="$(dirname "$0")"

# Prompt for sudo up front
sudo -v

#
# macOS Setup
#

# Configure common defaults
# source "$dir/system/defaults.sh"

#
# Run setup scripts
#

# source "$dir/system/brew.sh"
# source "$dir/system/zsh.sh"
# source "$dir/system/node.sh"
# source "$dir/system/ruby.sh"

#
# Install tools & apps
#

# source "$dir/brew/brews.sh"
# source "$dir/brew/casks.sh"
